### ISSUE TITLE
Hyphen in URL

### ISSUE THREAD

**Issue by Pacerino** [UrielCh/proxmox-api#1]
Hey there!

I've ran into a problem with the Qemu Agent. When i try to call _/nodes/{node}/qemu/{vmid}/agent/get-fsinfo_ Typescript will interpret the hyphen as a subtract and throw an error. Do you have an idea how i can fix this or some kind of workaround?

Greetings from germany!

![image](https://user-images.githubusercontent.com/22194063/95907016-38dc8480-0d9b-11eb-84c3-eb2a73dc078a.png)
![image](https://user-images.githubusercontent.com/22194063/95907153-69bcb980-0d9b-11eb-9cdf-9af0459ecc27.png)

**Comment by Pacerino** [comment]
Found a Workaround for this:
```javascript
theNode.qemu.$(vmid).agent["get-fsinfo"].$get()
```

Maybe this should me mentioned in the readme? @UrielCh

**Comment by UrielCh** [comment]
I never used any call with an Hyphen.

I will add a note about Hyphen for my next API update.

**Comment by UrielCh** [comment]
ReadMe updated.
