### ISSUE TITLE
All Get Params dont get send with the Request

### ISSUE THREAD

**Issue by DariusRDev** [UrielCh/proxmox-api#12]
![image](https://user-images.githubusercontent.com/77979816/188885113-fa5737e7-6f7c-4e0d-af3d-63203e37e892.png)

In line 99 i log the content of volume and filepath and it is set, but the api returns that volume and filepath are missing.

Has anybody an Idea why.

Thanks :D

**Comment by DariusRDev** [comment]
![image](https://user-images.githubusercontent.com/77979816/189343979-fa4c0e5f-db43-4319-955d-781082dde401.png)

Issue is thtat `theUrl.pathname` does not contain the query I will fix this in a pull Request

**Comment by DariusRDev** [comment]
Changed to 
![image](https://user-images.githubusercontent.com/77979816/189345455-4c9391b4-ff33-4857-b39c-80f8e513b5e8.png)

**Comment by UrielCh** [comment]
past code instead of passing screenshots, I gonna remove my tiny request code undici fetch is now part of nodeJS.

I will fix your issue during the update.

**Comment by UrielCh** [comment]
should be fixed in proxmox-api@0.4.0
