### ISSUE TITLE
FileRestore: unexpected contentType "application/octet-stream" 

### ISSUE THREAD

**Issue by DariusRDev** [UrielCh/proxmox-api#14]
This Request is needed to download a file from the file Restore

```
 let result = await proxmox.nodes
                .$("node02-prox")
                .storage.$("prox-back-02")
                ["file-restore"].download.$get({
                    volume: backup.volid,
                    filepath: .path,
                }
);

```

**Comment by DariusRDev** [comment]
Problem your tinyrequest Lib doesnt work with streams

**Comment by UrielCh** [comment]
undici gonna replace this tiny lib, past a code sample to help me to reproduce the issue. and fix this case.

**Comment by UrielCh** [comment]
just migrated to undici fetch, and need some test...

**Comment by UrielCh** [comment]
have you another call that returns a stream, I do not have any Proxmox Backup Server available here to test.

**Comment by DariusRDev** [comment]
Sry i dont now of any other endpoint

**Comment by UrielCh** [comment]
okey.

can I set up a `Proxmox Backup Server` inside a Proxmox and reference it from the Proxmox it runs on? that should be a valid test environment.

**Comment by UrielCh** [comment]
you can try V 0.4.2.
you will get back a { ReadableStream } from "stream/web"

**Comment by UrielCh** [comment]
let's say that it's fixed.
