### ISSUE TITLE
Support for No Port

### ISSUE THREAD

**Issue by bnjunge** [UrielCh/proxmox-api#16]
Is it possible to disable/remove the ```port```? My Proxmox proxy doesn't have the port, just a URL.

**Comment by UrielCh** [comment]
if your url starts with https://
the port is 443.

your welcome.

**Comment by bnjunge** [comment]
I mean if the port is null, the default is 8006 which autofills. This is what I would like to disable if possible. In my case, I have my proxmox url as a domain.tld with SSL as you had mentioned. When using the API, without port the url is https://domain.tld:8006 

This may need some changes here https://github.com/UrielCh/proxmox-api/blob/01cd442b13f36e0e3d04e4ac84bc6ddf040b44f8/api/src/ProxmoxEngine.ts#L128
and https://github.com/UrielCh/proxmox-api/blob/01cd442b13f36e0e3d04e4ac84bc6ddf040b44f8/api/src/ProxmoxEngine.ts#L291 just a sample.

If port could be optional that would be great for such use-cases if they arise

**Comment by UrielCh** [comment]
By default proxmox port is 8006, that why this is the default value, in all the cases you need a port, so it's more convenient that if you do not provide the port 8006 is provided, not 443.

maybe I do not understand your issue.

**Comment by bnjunge** [comment]
Well, I you're right, my request was to make the port completely optional such as
 ```const requestUrl = `${this.schema}://${this.host}/api2/json/access/ticket`;``` or use the ```.env``` HOST URL value together with port if one has implementations with/without
```PROXMOX_HOST=your_ip:port``` or ```PROXMOX_HOST=your_ip```

If proxmox is behind a proxy that masks the port, or is behind a tunnel like Cloudflare ZeroTrust tunnel, support for custom ports in such a case is limited and one is only allowed to use standard http ports(80, 443)

**Comment by UrielCh** [comment]
Excuse me, I was on other projects.

if you can open a PR, I remember that the Proxmox API uses some strange stuff, about port, due to the usage of a PVEProxy.

I will clean your PR, if the code is dirty.

**Comment by bnjunge** [comment]
Done.

**Comment by UrielCh** [comment]
thx, I closed you PR, can you open a new one with the same title and content?

my CLA trigger was not enabled.

then your PR will be merged and the next version of the project will be published the same day.

**Comment by UrielCh** [comment]
By the way, you are my first Kenyan contributor, that's a pleasure 👍

**Comment by bnjunge** [comment]
Thank you! I have open the PR.

**Comment by UrielCh** [comment]
it's partially failed, you have to go back to the PR to validate the CLA.
this time I can keep it.

**Comment by UrielCh** [comment]
up

**Comment by bnjunge** [comment]
Sorry was held up, will redo.

**Comment by UrielCh** [comment]
Note, I refactored your PR code.
V 1.0.2 is out.
