### ISSUE TITLE
custom-patch

### ISSUE THREAD

**Issue by Pribess** [UrielCh/proxmox-api#26]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `proxmox-api@1.0.2` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/proxmox-api/dist/esm/model.d.ts b/node_modules/proxmox-api/dist/esm/model.d.ts
index cb5cfa9..bf339f4 100644
--- a/node_modules/proxmox-api/dist/esm/model.d.ts
+++ b/node_modules/proxmox-api/dist/esm/model.d.ts
@@ -2735,7 +2735,7 @@ export declare namespace Proxmox {
         /**
          * Used memory in bytes (when type in node,qemu,lxc).
          */
-        mem?: string;
+        mem?: number;
         /**
          * Name of the resource.
          */
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by UrielCh** [comment]
so ... maybe the type had change with the new proxmox...
