### ISSUE TITLE
QEMU GA guest-exec not working correctly with PVE 8

### ISSUE THREAD

**Issue by lukasbableck** [UrielCh/proxmox-api#34]
I have encountered an issue with the /nodes/{node}/qemu/{vmid}/agent/exec endpoint. It seems that the command is not being passed correctly to the PVE API. According to the [PVE documentation](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/exec), it should be passed as an array, but it is actually passed as a string.
This probably occurs from PVE 8 onwards, but I can't say for sure as I only discovered this now on PVE 8.2.4. 

This is how I call the endpoint:
```
qemu.agent.exec.$post({ command: ['touch', '/test'] })
```
I have logged the fetch call, this is the result:
```
fetch("https://pve.example.com/api2/json/nodes/n/qemu/999/agent/exec", {"method":"POST","body":"command=touch%2C%2Ftest","headers":{"Accept":"*/*","User-Agent":"proxmox-api (https://github.com/UrielCh/proxmox-api)","Authorization":"PVEAPIToken=xyz","Content-Type":"application/x-www-form-urlencoded","Content-Length":"23"}})
```
Here is the important part: `"body":"command=touch%2C%2Ftest"`

This call produces the following syslog entry on the guest. As you can see, the command is not correct and will obviously not work like this:
![image](https://github.com/user-attachments/assets/365e4592-01d1-43b8-99e0-35a756979ab3)
This call also causes the PVE API to return status code 596 in addition.
\
\
The request body should look like this in that case:
```
command=touch&command=%2Ftest
```

This produces the correct result on the guest and the command works:
![image](https://github.com/user-attachments/assets/9dfd9886-7b85-4f02-b991-eaed18d15ee1)

**Comment by UrielCh** [comment]
so, the current genrerated body is

`command=touch%2C%2Ftest`

instread of:

`command=touch&command=%2Ftest`

is there any other rentry point having the same issue ?


there is 3 way to fix that within this lib:
- update the engine so eny array will be process as duplicate param.

or

- add an other method to handle that in some case.

or

- hard code an exception.

only one solution is the rigth one, I need to figure out which one is the right one.

**Comment by lukasbableck** [comment]
> so, the current genrerated body is
> command=touch%2C%2Ftest
> instread of:
> command=touch&command=%2Ftest

Correct.
 
 
 
> is there any other rentry point having the same issue ?

I'd imagine that every endpoint that accepts an array as an input has that problem. 
I have just tried it out with the POST /cluster/notifications/endpoints/sendmail endpoint with the mailto parameter. 
The problem also occurs here, although with a different response from the PVE API saying the email address is not valid, which is because it's again just all the addresses in the array concatenated with a comma.

**Comment by UrielCh** [comment]
nice, let me add some test unit to fix that properly

**Comment by UrielCh** [comment]
https://github.com/UrielCh/proxmox-api/pull/35

**Comment by UrielCh** [comment]
V 1.1.1 is out.

**Comment by lukasbableck** [comment]
1.1.1 fixes the issue for me, thank you very much!
