### ISSUE TITLE
Migrate VM in cluster 

### ISSUE THREAD

**Issue by Jbone187** [UrielCh/proxmox-api#37]
I am having a hard time featuring out how to migrate a VM to another cluster. I have looked at the docs but I'm not smart enough to follow lol

**Comment by UrielCh** [comment]
For now I do not have access to any proxmox.

Try to migrate your VM using the web-interface, capturing all traffic in your browser devtools, that will give you some hints about the proper way to migrate a VM using the API.

**Comment by Jbone187** [comment]
ok ty
