### ISSUE TITLE
support for version 7

### ISSUE THREAD

**Issue by DeanKamali** [UrielCh/proxmox-api#4]
I'm using PVE, version 7, they which includes a new API endpoint that deals with downloading ISOs, `download_url` [documented here ](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/download-url )

I think this package could use an update to include new mapping. 

Following the convention,  the API should work like so: 

```
const nodes = await pve.nodes.$get();
    // iterate cluster nodes
    for (const node of nodes) {
      const theNode = pve.nodes.$(node.node);
      theNode.storage.$('local').download_url.$post({
        url: 'https://download.iso'
      })
    }
```

**Comment by UrielCh** [comment]
Updating the project soon...
I'm back on proxmox this week

**Comment by UrielCh** [comment]
try the beta version:
```nash
npm install proxmox-api@beta
```

**Comment by UrielCh** [comment]
I'm using V7, and it works.
