### ISSUE TITLE
Can we change the license from GPL-3.0

### ISSUE THREAD

**Issue by tahergalal** [UrielCh/proxmox-api#7]
Is there a reason why the library is set to use GPL-3.0 becuse this will making the usage of the library a problem if someone uses it as all the code needs to be made public

**Comment by UrielCh** [comment]
I have to upgrade this project to a dual license.

is your project in an open-source license? or a closed one?

**Comment by tahergalal** [comment]
It is a closed source license. This is a lonrary from what I get that helps with calling the proxmox API

**Comment by tahergalal** [comment]
From what I can see this is a library that can be used to call the proxmox api. therefore having it as a GPL-3.0 license would cause no one to be able to use it of they care about the license. As this would mean any code using it needs to be fully available. Our code is a closed project therefore it would be an issue if we use this linrary for us. Maybe we can switch it to a more usable license?

**Comment by tahergalal** [comment]
if this is possible

**Comment by tahergalal** [comment]
any update on the possibility I can also create a pull request if it is ok with you to set the license?

**Comment by UrielCh** [comment]
The idea was to add a secondary license for commercial usage, but I did not find time to take care of that.

The second phase of the project is to release the plus version, which is not a pure Proxmox mapping.

Sorry for the delay.

**Comment by Mecanik** [comment]
There is no point in keeping the GNU license at this point. You already published the source, anyone can take it and used it inside closed quarters on a cloud service, you would never know it.

Make it MIT if you want any attention from your hard work, which is recognizable.

**Comment by UrielCh** [comment]
GPL V3 is not AGPL; feel free to use it in "closed quarters."

**Comment by Mecanik** [comment]
> GPL V3 is not AGPL; feel free to use it in "closed quarters."

You should not be sarcastic and try to do things properly if you want people to use your library.

With that being said, you should add dependencies for people...

```
  node_modules/busboy/lib/types/multipart.js:3:39: ERROR: Could not resolve "stream"
  node_modules/busboy/lib/types/urlencoded.js:3:29: ERROR: Could not resolve "stream"
  node_modules/proxmox-api/dist/esm/ProxmoxEngine.js:17:20: ERROR: Could not resolve "url"
  node_modules/undici/lib/api/api-connect.js:4:34: ERROR: Could not resolve "async_hooks"
  node_modules/undici/lib/api/api-pipeline.js:7:12: ERROR: Could not resolve "stream"
```

And these are just a few. Frankly the headache of adding them and resolving problems makes this library useless.

Better for a user to do a simple fetch and be done with it.

I'm out.

**Comment by jcads** [comment]
@Mecanik how did you fixed the "async_hooks" dependency issue?
